import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import "react-toastify/dist/ReactToastify.css";
import Myroutes from "./route/MyRoutes";
import { BrowserRouter } from "react-router-dom";
import NavBar from "./components/NavBar";
import { Provider } from "react-redux";
import { store } from "./store/store";
import { ToastContainer } from "react-toastify";
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
  resources: {
    en: {
      translation: {
        profileupdate: "Profile Updated!",
        productcreated: "Product Created!",
        productedited: "Product Edited!",
        productdeleted: "Product Deleted!",
        userdeleted: "User Deleted!",
        increasedaproduct: "Increased a product!",
        decreasedaproduct: "Decreased a product!",
        addproducttocart: "Product added to cart!",
        removeproducttocart: "Product removed from cart!",
        cartcleared: "Cart cleared!",
        advertisingcreated: "Advertising Created!",
        advertisingdeleted: "Advertising Deleted!",
        lenguaje1: "English",
        lenguaje2: "ES",
        users: "Users",
        quicklinks: "Links",
        summary: "Summary",
        products: "Products",
        orders: "Orders",
        banners: "Banners",
        create: "Create",
        delete: "Delete",
        view: "View",
        pending: "Pending",
        dispatched: "Dispatched",
        delivered: "Delivered",
        dispatch: "Dispatch",
        deliver: "Deliver",
        edit: "Edit",
        editproduct: "Edit Product",
        editaproduct: "Edit a Product",
        selectbrand: "Select Brand",
        other: "Other",
        imagepreview: "Image Preview",
        cancel: "Cancel",
        admin: "Admin",
        customer: "Customer",
        createaproduct: "Create a Product",
        submit: "Submit",
        login: "Login",
        register: "Register",
        loading: "Loading ...",
        orderdetails: "Order Details",
        orderproducts: "Order Products",
        totalprice: "Total Price",
        shippingdetails: "Shipping Details",
        name: "Name",
        city: "City",
        email: "Email",
        brand: "Brand",
        description: "Description",
        addtocart: "Add to Cart",
        userprofile: "User Profile",
        password: "New Password",
        shoppingcart: "Shopping Cart",
        cartempty: "Your cart is currently empty!",
        startshopping: "Start Shopping",
        product: "Product",
        price: "Price",
        quantity: "Quantity",
        total: "Total",
        remove: "Remove",
        clearcart: "Clear Cart",
        taxesshipping: "Taxes and shipping calculated at checkout",
        logintocheckout: "Login to check out",
        continueshopping: "Continue Shopping",
        deliverystatus: "Delivery Status",
        checkoutsuccess: "Checkout Successful",
        statusorder: "Your order might take some time to process",
        statusorder2:
          "Check your order status at your profile after about 5 mins",
        support: "Incase of any inquieres contact the support at",
        tecnology: "Tecnology",
        unexpectederror: "Unexpected error occured...",
        mostselled: "Most selled products",
        paymentmethods: "Payment methods",
        categories: "Categories",
        monitors: "Monitors",
        peripherals: "Peripherals",
        graphics: "Graphics",
        disks: "Disks",
        cart: "Cart",
        logout: "Logout",
        checkout: "Check Out",
        createabanner: "Create a Banner",
        alltime: "Comprehensive Performance",
        earnings: "Earnings",
        loadingchart: "Loading Chart ...",
        transactionsloading: "Transactions loading...",
        latesttransaction: "Latest Transaction",
        accessdenied: "Access denied",
        overview: "Overview",
        messagecompare:
          "How your business is performing compared to the previous month",
        earning7days: "Weekly earnings ",
        earning30days: "Monthly earnings ",
        monthly: "Show Monthly Graph",
        weekly: "Show Weekly Chart",
        account: "Account",
        orders2: "My Orders",
        nameuser: "Name",
        amountuser: "Amount",
        statususer: "Status",
        dateuser: "Date",
        imageuser: "Image",
        descriptionuser: "Description",
        priceuser: "Price",
        actionsuser: "Actions",
        emailuser: "Email",
        roleuser: "Role",
        submitting: "Submitting...",
        oldpassword: "Password",
        back: "Back",
      },
    },
    es: {
      translation: {
        profileupdate: "Perfil Actualizado!",
        productcreated: "Producto Creado!",
        productedited: "Producto Editado!",
        productdeleted: "Producto Eliminado!",
        userdeleted: "Usuario Eliminado!",
        increasedaproduct: "Aumento un producto!",
        decreasedaproduct: "Disminuyo un producto!",
        addproducttocart: "Producto añadido al carrito!",
        removeproducttocart: "Producto eliminado del carrito!",
        cartcleared: "Carrito vacio!",
        advertisingcreated: "Anuncio Creado!",
        advertisingdeleted: "Anuncio Eliminado!",
        lenguaje1: "EN",
        lenguaje2: "Spanish",
        users: "Usuarios",
        quicklinks: "Enlaces",
        summary: "Resumen",
        products: "Productos",
        orders: "Ordenes",
        banners: "Anuncios",
        create: "Crear",
        delete: "Eliminar",
        view: "Vista",
        pending: "Pendiente",
        dispatched: "Despachado",
        delivered: "Entregado",
        dispatch: "Despacho",
        deliver: "Entregar",
        edit: "Editar",
        editproduct: "Editar Producto",
        editaproduct: "Editar un Producto",
        selectbrand: "Selecciona marca",
        other: "Otro",
        imagepreview: "Imagen Previa",
        cancel: "Cancelar",
        admin: "Admin",
        customer: "Cliente",
        createaproduct: "Crear un Producto",
        submit: "Enviar",
        login: "Iniciar Sesion",
        register: "Registrar",
        loading: "Cargando ...",
        orderdetails: "Detalle de Orden",
        orderproducts: "Orden de Productos",
        totalprice: "Precio Total",
        shippingdetails: "Detalle de Envio",
        name: "Nombre",
        city: "Ciudad",
        email: "Correo",
        brand: "Marca",
        description: "Descripcion",
        addtocart: "Agregar al carrito",
        userprofile: "Perfil de Usuario",
        password: "Nueva Contraseña",
        shoppingcart: "Carrito de Compras",
        cartempty: "Su carrito de compras esta vacio!",
        startshopping: "Empieza a comprar!",
        product: "Producto",
        price: "Precio",
        quantity: "Cantidad",
        total: "Total",
        remove: "Remover",
        clearcart: "Limpiar Carrito",
        taxesshipping: "Impuestos y envío calculados al finalizar la compra",
        logintocheckout: "Inicia sesión para comprobar",
        continueshopping: "Continuar Comprando",
        deliverystatus: "Estado de Entrega",
        checkoutsuccess: "Pago Exitoso",
        statusorder: "Su pedido puede tardar algún tiempo en procesarse",
        statusorder2:
          "Verifique el estado de su pedido en su perfil después de unos 5 minutos",
        support: "En caso de cualquier consulta comuníquese con el soporte a",
        tecnology: "Tecnologia",
        unexpectederror: "Ocurrió un error inesperado...",
        mostselled: "Productos más vendidos",
        paymentmethods: "Metodos de pago",
        categories: "Categorias",
        monitors: "Monitores",
        peripherals: "Perifericos",
        graphics: "Graficos",
        disks: "Discos",
        cart: "Carrito",
        logout: "Cerrar Sesion",
        checkout: "Verificar",
        createabanner: "Crear un Anuncio",
        alltime: "Rendimiento Integral",
        earnings: "Ganancias",
        loadingchart: "Cargando Grafico ...",
        transactionsloading: "Cargando transacciones ...",
        latesttransaction: "Ultima transacción",
        accessdenied: "Acceso Denegado",
        overview: "Descripcion General",
        messagecompare:
          "Cómo se está desempeñando su negocio en comparación con el mes anterior",
        earning7days: "Ganancias semanales ",
        earning30days: "Ganancias Mensuales ",
        monthly: "Mostrar Grafico Mensual",
        weekly: "Mostrar Grafico Semanal",
        orders2: "Mis Pedidos",
        account: "Mi Cuenta",
        nameuser: "Nombre",
        amountuser: "Cantidad (S/.)",
        statususer: "Estado",
        dateuser: "Fecha",
        imageuser: "Imagen",
        descriptionuser: "Descripcion",
        priceuser: "Precio",
        actionsuser: "Acciones",
        emailuser: "Correo",
        roleuser: "Cargo",
        submitting: "Entregando...",
        oldpassword: "Contraseña",
        back: "Regresar",
      },
    },
  },
  lng: "es", // Establece el idioma predeterminado
  fallbackLng: "es", // Idioma de respaldo en caso de que no se encuentre una traducción
});

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <Provider store={store}>
      <BrowserRouter>
        <ToastContainer />
        <NavBar />
        <Myroutes />
      </BrowserRouter>
    </Provider>
  </React.StrictMode>
);
